@echo off
"@echo off"
"rem Robust run_backend.bat - use repository-relative paths and venv detection"
"rem Usage: double-click or run from cmd"
""
"rem Determine script directory (repo root)"
"set SCRIPT_DIR=%~dp0"
"rem change working directory to repo root"
"pushd \"%SCRIPT_DIR%\""
""
"rem detect venv python"
"set \"PY_EXE=\""
"if exist \"%SCRIPT_DIR%\\.venv_backtest\\Scripts\\python.exe\" ("
"  set \"PY_EXE=%SCRIPT_DIR%\\.venv_backtest\\Scripts\\python.exe\""
" ) else if exist \"%SCRIPT_DIR%\\.venv_new\\Scripts\\python.exe\" ("
"  set \"PY_EXE=%SCRIPT_DIR%\\.venv_new\\Scripts\\python.exe\""
" ) else ("
"  set \"PY_EXE=python\""
" )"
""
"if not exist \"backtesting_backend\\logs\" mkdir \"backtesting_backend\\logs\""
""
"echo Starting backtesting uvicorn using %PY_EXE%"
"\"%PY_EXE%\" -m uvicorn backtesting_backend.app_main:app --host 0.0.0.0 --port 8001 > \"backtesting_backend\\logs\\uvicorn.log\" 2>&1"
""
"popd"
"C:\Users\User\new\YONA Vanguard Futures(new)\.venv_backtest\Scripts\python.exe" -m uvicorn backtesting_backend.app_main:app --host 0.0.0.0 --port 8001 > "backtesting_backend\logs\uvicorn.log" 2>&1
