"""
테스트넷 실행 검증 가이드
- .env 파일 확인
- run_live_verification.py 실행 전 체크리스트
- 예상 결과
"""

print("=" * 80)
print("테스트넷 실행 검증 가이드")
print("=" * 80)

print("\n📋 사전 준비 사항:")
print("-" * 80)
print("1. Binance Testnet API 키 발급")
print("   - https://testnet.binancefuture.com/ 접속")
print("   - 계정 생성 및 로그인")
print("   - API Management → Create API Key")
print("   - API Key & Secret Key 복사")
print("")
print("2. .env 파일 설정")
print("   - 프로젝트 루트의 .env 파일 열기")
print("   - BINANCE_API_KEY=<your_testnet_api_key>")
print("   - BINANCE_SECRET_KEY=<your_testnet_secret_key>")
print("   - BINANCE_BASE_URL=https://testnet.binancefuture.com")
print("")
print("3. 테스트넷 잔고 충전")
print("   - Testnet 사이트에서 'Get Test Funds' 클릭")
print("   - 10,000 USDT 테스트 자금 수령")
print("-" * 80)

print("\n🔍 검증 스크립트 실행:")
print("-" * 80)
print("명령어:")
print("  python run_live_verification.py")
print("")
print("검증 단계 (총 8단계):")
print("  [1/8] BinanceClient 초기화 (API 키 로드)")
print("  [2/8] 계좌 정보 조회 (totalWalletBalance, availableBalance)")
print("  [3/8] 심볼 설정 (레버리지 10x, ISOLATED 마진)")
print("  [4/8] 실시간 캔들 데이터 조회 (1m, limit=5)")
print("  [5/8] 거래 필터 검증 (minNotional, stepSize)")
print("  [6/8] Orchestrator 초기화")
print("  [7/8] 데이터 Warmup (1m/3m/15m 200개씩)")
print("  [8/8] 단일 Step 실행 (진입 신호 확인)")
print("-" * 80)

print("\n✅ 예상 결과:")
print("-" * 80)
print("정상 실행 시:")
print("  ✅ [1/8] BinanceClient 초기화 성공")
print("  ✅ [2/8] 계좌 정보: totalWalletBalance=10000.0, availableBalance=10000.0")
print("  ✅ [3/8] 레버리지 10x 설정 완료, 마진 타입: ISOLATED")
print("  ✅ [4/8] 실시간 캔들 5개 조회 완료")
print("  ✅ [5/8] 필터 검증: minNotional=5.0, stepSize=0.001")
print("  ✅ [6/8] Orchestrator 초기화 완료")
print("  ✅ [7/8] Warmup 완료: 1m=200, 3m=200, 15m=200")
print("  ✅ [8/8] Step 실행 완료: entry_triggered=False/True")
print("")
print("오류 발생 시:")
print("  ❌ API 키 오류: Invalid API-key, IP, or permissions")
print("    → .env 파일의 API 키 확인")
print("  ❌ 잔고 부족: Insufficient balance")
print("    → 테스트넷에서 테스트 자금 수령")
print("  ❌ 레버리지 설정 실패: Leverage not changed")
print("    → 이미 설정되어 있음 (정상)")
print("-" * 80)

print("\n🚀 다음 단계 (검증 통과 후):")
print("-" * 80)
print("1. Backend 서버 실행")
print("   python backend/app_main.py")
print("")
print("2. GUI 실행 (별도 터미널)")
print("   python gui/main.py")
print("")
print("3. GUI에서 NewModular 엔진 시작")
print("   - 상단 START 버튼 클릭 (앱 시작)")
print("   - 하단 NewModular 섹션의 START 버튼 클릭")
print("   - Symbol: BTCUSDT (기본값)")
print("   - Leverage: 10x")
print("   - Apply 버튼 클릭")
print("")
print("4. 실시간 모니터링")
print("   - Backend 로그: logs/strategy/Orchestrator_YYYYMMDD.log")
print("   - 거래 로그: logs/strategy/Orchestrator_trades_YYYYMMDD.log")
print("   - GUI: NewModular 섹션의 에너지 분석, 거래 메시지 확인")
print("")
print("5. 소액 테스트")
print("   - 최소 수량 (0.001 BTC) 설정")
print("   - 1시간 모니터링")
print("   - 진입/청산 로그 확인")
print("   - PNL 정확성 검증")
print("-" * 80)

print("\n⚠️  주의사항:")
print("-" * 80)
print("1. 테스트넷과 실전 환경은 다릅니다:")
print("   - 테스트넷: 슬리피지/체결 지연 거의 없음")
print("   - 실전: 변동성 높을 때 슬리피지/미체결 발생 가능")
print("")
print("2. 실전 투입 전 확인 사항:")
print("   - 백테스트 결과 (승률, MDD, Sharpe) 검증")
print("   - 테스트넷 1주일 이상 안정적 운영")
print("   - 리스크 관리 로직 (손절, 본절, 트레일링) 동작 확인")
print("   - 예상치 못한 상황 대응 (API 오류, 네트워크 단절)")
print("")
print("3. 실전 투입 시작 시:")
print("   - .env 파일을 실전 API 키로 변경")
print("   - BINANCE_BASE_URL=https://fapi.binance.com")
print("   - 최소 금액 (10~50 USDT)으로 시작")
print("   - 1~2주 모니터링 후 점진적 증액")
print("-" * 80)

print("\n" + "=" * 80)
print("준비가 되었으면 다음 명령어를 실행하세요:")
print("  python run_live_verification.py")
print("=" * 80)
